<?php

use Illuminate\Database\Seeder;

class GestionesRespuestasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        set_time_limit(0);

        $array_records = array (
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 54, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 14, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 26, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 57, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 40, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 3, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 15, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 9, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 10, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 1, 'respuestas_idrespuesta' => 11, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 2, 'respuestas_idrespuesta' => 3, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 2, 'respuestas_idrespuesta' => 5, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 2, 'respuestas_idrespuesta' => 45, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 2, 'respuestas_idrespuesta' => 47, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 3, 'respuestas_idrespuesta' => 33, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 56, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 57, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 40, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 1, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 2, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 5, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 7, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 8, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 34, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 53, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 5, 'respuestas_idrespuesta' => 20, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 12, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 54, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 13, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 39, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 27, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 14, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 26, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 15, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 7, 'respuestas_idrespuesta' => 9, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 8, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 9, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 9, 'respuestas_idrespuesta' => 21, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 10, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 10, 'respuestas_idrespuesta' => 23, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 11, 'respuestas_idrespuesta' => 23, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 11, 'respuestas_idrespuesta' => 4, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 12, 'respuestas_idrespuesta' => 22, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 12, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 12, 'respuestas_idrespuesta' => 55, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 12, 'respuestas_idrespuesta' => 47, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 14, 'respuestas_idrespuesta' => 6, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 12, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 54, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 13, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 39, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 27, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 14, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 26, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 15, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 15, 'respuestas_idrespuesta' => 9, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 16, 'respuestas_idrespuesta' => 29, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 16, 'respuestas_idrespuesta' => 30, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 16, 'respuestas_idrespuesta' => 9, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 54, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 12, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 13, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 39, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 27, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 14, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 26, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 15, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 17, 'respuestas_idrespuesta' => 10, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 18, 'respuestas_idrespuesta' => 24, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 19, 'respuestas_idrespuesta' => 46, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 20, 'respuestas_idrespuesta' => 31, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 21, 'respuestas_idrespuesta' => 32, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 22, 'respuestas_idrespuesta' => 4, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 22, 'respuestas_idrespuesta' => 46, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 22, 'respuestas_idrespuesta' => 51, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 22, 'respuestas_idrespuesta' => 52, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 26, 'respuestas_idrespuesta' => 15, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 38, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 25, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 28, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 58, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 59, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 41, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 42, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 32, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 43, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 44, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 4, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 46, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 18, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 16, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 19, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 48, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 17, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 35, 'created_at' => date('Y-m-d')),
            array('gestiones_idgestiones' => 27, 'respuestas_idrespuesta' => 36, 'created_at' => date('Y-m-d')),
        );

        foreach (array_chunk($array_records, 1000) as $records) {
              \DB::table('gestiones_respuestas')->insert($records);
        }
    }
}
