<?php

use Illuminate\Database\Seeder;

class RespuestaDetallesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	set_time_limit(0);

        $array_records = array (
	        array('respuestas_idrespuesta' => 1, 'respuestas_codigo_respuesta' => 'B001', 'literal' => 'A', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 1, 'respuestas_codigo_respuesta' => 'B001', 'literal' => 'B', 'detalle' => 'TERMINADO CON NUEVO DOCUMENTO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 2, 'respuestas_codigo_respuesta' => 'B002', 'literal' => 'A', 'detalle' => 'EN CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 3, 'respuestas_codigo_respuesta' => 'B003', 'literal' => 'A', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 3, 'respuestas_codigo_respuesta' => 'B003', 'literal' => 'B', 'detalle' => 'EN CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 3, 'respuestas_codigo_respuesta' => 'B003', 'literal' => 'C', 'detalle' => 'DEPOSITO EN CTA.CTE.', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 4, 'respuestas_codigo_respuesta' => 'B004', 'literal' => 'A', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 5, 'respuestas_codigo_respuesta' => 'B005', 'literal' => 'A', 'detalle' => 'CLIENTE NUEVO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 5, 'respuestas_codigo_respuesta' => 'B005', 'literal' => 'B', 'detalle' => 'REASIGNACIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 6, 'respuestas_codigo_respuesta' => 'B006', 'literal' => 'A', 'detalle' => 'CONTINUAR BUSQUEDA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 7, 'respuestas_codigo_respuesta' => 'B007', 'literal' => 'A', 'detalle' => 'DEUDOR REASIGNADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 8, 'respuestas_codigo_respuesta' => 'B008', 'literal' => 'A', 'detalle' => 'DEUDOR SIN FONO CONTACTO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 9, 'respuestas_codigo_respuesta' => 'B009', 'literal' => 'A', 'detalle' => 'CLIENTE ESCUCHA Y CORTA LLAMADO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 10, 'respuestas_codigo_respuesta' => 'B010', 'literal' => 'A', 'detalle' => 'A REGULARIZAR DEUDA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 10, 'respuestas_codigo_respuesta' => 'B010', 'literal' => 'B', 'detalle' => 'PARA HACER RECLAMO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 11, 'respuestas_codigo_respuesta' => 'B011', 'literal' => 'A', 'detalle' => 'PROBLEMAS ECONOMICOS', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 11, 'respuestas_codigo_respuesta' => 'B011', 'literal' => 'B', 'detalle' => 'ESTA CESANTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 11, 'respuestas_codigo_respuesta' => 'B011', 'literal' => 'C', 'detalle' => 'DEUDOR FALLECIO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 12, 'respuestas_codigo_respuesta' => 'B012', 'literal' => 'A', 'detalle' => 'DEUDOR SOLICITA COPIA BOLETA O EST.CUENT', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 12, 'respuestas_codigo_respuesta' => 'B012', 'literal' => 'B', 'detalle' => 'BOLETA ENVIADA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 13, 'respuestas_codigo_respuesta' => 'B013', 'literal' => 'A', 'detalle' => 'CLIENTE SOLICITA VOLVER A LLAMAR', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 14, 'respuestas_codigo_respuesta' => 'B014', 'literal' => 'A', 'detalle' => 'DESCONOCE SERVICIO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 14, 'respuestas_codigo_respuesta' => 'B014', 'literal' => 'B', 'detalle' => 'RENUNCIO A SERVICIO O CONTRATO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 14, 'respuestas_codigo_respuesta' => 'B014', 'literal' => 'C', 'detalle' => 'TIENE RECLAMO SIN RESPONDER', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 14, 'respuestas_codigo_respuesta' => 'B014', 'literal' => 'D', 'detalle' => 'DIFERENCIA EN DEUDA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 15, 'respuestas_codigo_respuesta' => 'B015', 'literal' => 'A', 'detalle' => 'TIENE RECLAMO AL CLIENTE SIN RESPONDER', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 15, 'respuestas_codigo_respuesta' => 'B015', 'literal' => 'B', 'detalle' => 'NIEGA PRODUCTO O SERVICIO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 15, 'respuestas_codigo_respuesta' => 'B015', 'literal' => 'C', 'detalle' => 'NO HA RECIBIDO FACTURA O BOLETA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 15, 'respuestas_codigo_respuesta' => 'B015', 'literal' => 'D', 'detalle' => 'ANULO CONTRATO, CUENTA O COMPRA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'A', 'detalle' => 'OFICINA CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'B', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'C', 'detalle' => 'SERVIAPAG / SENCILLITO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'D', 'detalle' => 'OTRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'E', 'detalle' => 'PIDE RETIRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'F', 'detalle' => 'OFICINA CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'G', 'detalle' => 'VENDRA A OFICINA ', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'H', 'detalle' => 'ENVIARA DOCUMENTO (CHEQUE)', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'I', 'detalle' => 'DEPOSITARA EN CTA. CTE. OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'J', 'detalle' => 'ENVIARA GIRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'K', 'detalle' => 'EN BANCO O PAC', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'L', 'detalle' => 'EN SERVIPAG - SENCILLITO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'M', 'detalle' => 'CUPON DE PAGO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 16, 'respuestas_codigo_respuesta' => 'B016', 'literal' => 'N', 'detalle' => 'LLAMAR POR FECHA DE PAGO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'A', 'detalle' => 'OFICINA CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'B', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'C', 'detalle' => 'OTRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'D', 'detalle' => 'EN CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'E', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'F', 'detalle' => 'EN SERVIPAG - SENCILLITO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'G', 'detalle' => 'EN BANCO O TIENE PAC', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'H', 'detalle' => 'A COBRADOR', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'I', 'detalle' => 'CUPON DE PAGO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'J', 'detalle' => 'ANULO EN CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'K', 'detalle' => 'HIZO CONVENIO EN CLIENTE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 17, 'respuestas_codigo_respuesta' => 'B017', 'literal' => 'L', 'detalle' => 'TIENE PAM FALABELLA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 18, 'respuestas_codigo_respuesta' => 'B018', 'literal' => 'A', 'detalle' => 'NO EXISTE NÚMERO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 18, 'respuestas_codigo_respuesta' => 'B018', 'literal' => 'B', 'detalle' => 'FALTA INFORMACIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 18, 'respuestas_codigo_respuesta' => 'B018', 'literal' => 'C', 'detalle' => 'DIRECCIÓN INCONSISTENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'A', 'detalle' => 'SE CAMBIÓ', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'B', 'detalle' => 'DESCONOCIDO EN DIRECCIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'C', 'detalle' => 'NUEVOS ARRENDATARIOS', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'D', 'detalle' => 'SE CAMBIO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'E', 'detalle' => 'NO CONOCE A DEUDOR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'F', 'detalle' => 'NO EXISTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'G', 'detalle' => 'ES INUBICABLE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'H', 'detalle' => 'Nº NO SE ENCONTRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 19, 'respuestas_codigo_respuesta' => 'B019', 'literal' => 'I', 'detalle' => 'DIRECCION INCOMPLETA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 20, 'respuestas_codigo_respuesta' => 'B020', 'literal' => 'A', 'detalle' => 'DEUDOR EN GESTION', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 20, 'respuestas_codigo_respuesta' => 'B020', 'literal' => 'B', 'detalle' => 'INTENTO LLAMADO NO LOGRADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 21, 'respuestas_codigo_respuesta' => 'B021', 'literal' => 'A', 'detalle' => 'INHABILITACION DE TAG', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 22, 'respuestas_codigo_respuesta' => 'B022', 'literal' => 'A', 'detalle' => 'SOLICITA COPIA BOLETAS', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 22, 'respuestas_codigo_respuesta' => 'B022', 'literal' => 'B', 'detalle' => 'SOLICITA DETALLE DEUDA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 22, 'respuestas_codigo_respuesta' => 'B022', 'literal' => 'C', 'detalle' => 'SOLICITA FORMAS Y LUGARES DE PAGO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 23, 'respuestas_codigo_respuesta' => 'B023', 'literal' => 'A', 'detalle' => 'DESDE OFICINA DE COBRO A DEUDOR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 23, 'respuestas_codigo_respuesta' => 'B023', 'literal' => 'B', 'detalle' => 'ENVIO MASIVO CON EXITO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 23, 'respuestas_codigo_respuesta' => 'B023', 'literal' => 'C', 'detalle' => 'ENVIO MASIVO SIN EXITO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 23, 'respuestas_codigo_respuesta' => 'B023', 'literal' => 'D', 'detalle' => 'RECEPCIÓN DE MAIL', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 24, 'respuestas_codigo_respuesta' => 'B024', 'literal' => 'A', 'detalle' => 'ENVIADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 24, 'respuestas_codigo_respuesta' => 'B024', 'literal' => 'B', 'detalle' => 'ENVÍO FALLIDO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 25, 'respuestas_codigo_respuesta' => 'B025', 'literal' => 'A', 'detalle' => 'FALLECIDO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 26, 'respuestas_codigo_respuesta' => 'B026', 'literal' => 'A', 'detalle' => 'F/SERVICIO, REPARACION, VACANTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 27, 'respuestas_codigo_respuesta' => 'B027', 'literal' => 'A', 'detalle' => 'NUEVOS ARRENDATARIOS', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 27, 'respuestas_codigo_respuesta' => 'B027', 'literal' => 'B', 'detalle' => 'SE CAMBIO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 27, 'respuestas_codigo_respuesta' => 'B027', 'literal' => 'C', 'detalle' => 'NO CONOCE A DEUDOR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 28, 'respuestas_codigo_respuesta' => 'B028', 'literal' => 'A', 'detalle' => 'FUERA DE AREA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 29, 'respuestas_codigo_respuesta' => 'B029', 'literal' => 'A', 'detalle' => 'GRABACIÓN COMPLETA ENTREGADA A PERSONA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 29, 'respuestas_codigo_respuesta' => 'B029', 'literal' => 'B', 'detalle' => 'GRABACIÓN COMPLETA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 29, 'respuestas_codigo_respuesta' => 'B029', 'literal' => 'C', 'detalle' => 'CONTESTA GRABADORA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 30, 'respuestas_codigo_respuesta' => 'B030', 'literal' => 'A', 'detalle' => 'FONO OCUPADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 30, 'respuestas_codigo_respuesta' => 'B030', 'literal' => 'B', 'detalle' => 'FONO NO CONTESTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 30, 'respuestas_codigo_respuesta' => 'B030', 'literal' => 'C', 'detalle' => 'FONO FAX', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 30, 'respuestas_codigo_respuesta' => 'B030', 'literal' => 'D', 'detalle' => 'FONO NO CONTACTADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 31, 'respuestas_codigo_respuesta' => 'B031', 'literal' => 'A', 'detalle' => 'ABIERTO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 31, 'respuestas_codigo_respuesta' => 'B031', 'literal' => 'B', 'detalle' => 'CERRADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'A', 'detalle' => 'CARTA ENTREGADA DIRECCION CORRECTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'B', 'detalle' => 'DEUDOR CAMBIO DOMICILIO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'C', 'detalle' => 'DEVUELTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'D', 'detalle' => 'REENVIO POR CORREOS DE CHILE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'E', 'detalle' => 'DEVUELTA POR FALTA DE DATOS', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'F', 'detalle' => 'LUGAR SIN MORADORES', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'G', 'detalle' => 'DIRECCION INSUFICIENTE O ERRONEA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'H', 'detalle' => 'SE NIEGAN A RECIBIR CARTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'I', 'detalle' => 'CARTA RECHAZA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'J', 'detalle' => 'NO HAY QUIEN RECIBA CARTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 32, 'respuestas_codigo_respuesta' => 'B032', 'literal' => 'K', 'detalle' => 'LUGAR IN...', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 33, 'respuestas_codigo_respuesta' => 'B033', 'literal' => 'A', 'detalle' => 'DESDE WEB OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 34, 'respuestas_codigo_respuesta' => 'B034', 'literal' => 'A', 'detalle' => 'DESDE CLIENTES', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 34, 'respuestas_codigo_respuesta' => 'B034', 'literal' => 'B', 'detalle' => 'DESDE OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 35, 'respuestas_codigo_respuesta' => 'B035', 'literal' => 'A', 'detalle' => 'TELEFONICAMENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 35, 'respuestas_codigo_respuesta' => 'B035', 'literal' => 'B', 'detalle' => 'POR DIRECCION Y TELEFONO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 35, 'respuestas_codigo_respuesta' => 'B035', 'literal' => 'C', 'detalle' => 'INUBICABLE ABSOLUTO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 36, 'respuestas_codigo_respuesta' => 'B036', 'literal' => 'A', 'detalle' => 'SECTOR PELIGROSO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 36, 'respuestas_codigo_respuesta' => 'B036', 'literal' => 'B', 'detalle' => 'RECINTO CERRADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 36, 'respuestas_codigo_respuesta' => 'B036', 'literal' => 'C', 'detalle' => 'NO PERMITEN ACCESO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 37, 'respuestas_codigo_respuesta' => 'B037', 'literal' => 'A', 'detalle' => 'CON TERCERO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 37, 'respuestas_codigo_respuesta' => 'B037', 'literal' => 'B', 'detalle' => 'CONTESTA MENOR DE EDAD', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 38, 'respuestas_codigo_respuesta' => 'B038', 'literal' => 'A', 'detalle' => 'SE CONFIRMA DIRECCIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 38, 'respuestas_codigo_respuesta' => 'B038', 'literal' => 'B', 'detalle' => 'SE DEJA NOTIFICACIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 38, 'respuestas_codigo_respuesta' => 'B038', 'literal' => 'C', 'detalle' => 'NO SE CONFIRMA DIRECCIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 39, 'respuestas_codigo_respuesta' => 'B039', 'literal' => 'A', 'detalle' => 'NO CONTESTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 39, 'respuestas_codigo_respuesta' => 'B039', 'literal' => 'B', 'detalle' => 'FONO OCUPADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 39, 'respuestas_codigo_respuesta' => 'B039', 'literal' => 'C', 'detalle' => 'CONTESTA FAX', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 39, 'respuestas_codigo_respuesta' => 'B039', 'literal' => 'D', 'detalle' => 'MENSAJE EN GRABADORA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 40, 'respuestas_codigo_respuesta' => 'B040', 'literal' => 'A', 'detalle' => 'TUVO PROBLEMAS ECONOMICOS', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 40, 'respuestas_codigo_respuesta' => 'B040', 'literal' => 'B', 'detalle' => 'SOLICITA OTRA FECHA DE PAGO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 41, 'respuestas_codigo_respuesta' => 'B041', 'literal' => 'A', 'detalle' => 'SE DEJA NOTIFICACIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 42, 'respuestas_codigo_respuesta' => 'B042', 'literal' => 'A', 'detalle' => 'CON TERCERO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 42, 'respuestas_codigo_respuesta' => 'B042', 'literal' => 'B', 'detalle' => 'CON DEUDOR SIN ACUERDO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 42, 'respuestas_codigo_respuesta' => 'B042', 'literal' => 'C', 'detalle' => 'DEUDOR IRA A CLIENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 42, 'respuestas_codigo_respuesta' => 'B042', 'literal' => 'D', 'detalle' => 'DEUDOR IRA A OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 42, 'respuestas_codigo_respuesta' => 'B042', 'literal' => 'E', 'detalle' => 'CON DEUDOR CON ACUERDO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 43, 'respuestas_codigo_respuesta' => 'B043', 'literal' => 'A', 'detalle' => 'SE DEJA NOTIFICACIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 44, 'respuestas_codigo_respuesta' => 'B044', 'literal' => 'A', 'detalle' => 'SIN ACUERDO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 45, 'respuestas_codigo_respuesta' => 'B045', 'literal' => 'A', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 45, 'respuestas_codigo_respuesta' => 'B045', 'literal' => 'B', 'detalle' => 'A COBRADOR OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 46, 'respuestas_codigo_respuesta' => 'B046', 'literal' => 'A', 'detalle' => 'EN OFICINA DE COBRO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 46, 'respuestas_codigo_respuesta' => 'B046', 'literal' => 'B', 'detalle' => 'EN ATENCIÓN CLIENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 47, 'respuestas_codigo_respuesta' => 'B047', 'literal' => 'A', 'detalle' => 'DEUDOR INDICA TENER PAC/PAT', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 47, 'respuestas_codigo_respuesta' => 'B047', 'literal' => 'B', 'detalle' => 'EMPRESA EN QUIEBRA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 47, 'respuestas_codigo_respuesta' => 'B047', 'literal' => 'C', 'detalle' => 'DEUDOR FALLECIO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 47, 'respuestas_codigo_respuesta' => 'B047', 'literal' => 'D', 'detalle' => 'TIENE RECLAMO SIN RESPONDER', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 47, 'respuestas_codigo_respuesta' => 'B047', 'literal' => 'E', 'detalle' => 'TIENE NOTA DE CREDITO PENDIENE', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 47, 'respuestas_codigo_respuesta' => 'B047', 'literal' => 'F', 'detalle' => 'OTRO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'A', 'detalle' => 'PROBLEMAS DE ATENCIÓN EJECUTIVO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'B', 'detalle' => 'FONO NO CORRESPONDE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'C', 'detalle' => 'MAIL NO CORRESPONDE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'D', 'detalle' => 'DIRECCIÓN NO CORRESPONDE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'E', 'detalle' => 'CUENTA YA REGULARIZADA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'F', 'detalle' => 'DESCONOCE DEUDA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'G', 'detalle' => 'HOSTIGAMIENTO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'H', 'detalle' => 'SE ENTREGA INFORMACIÓN DE DEUDA A TERCER', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'I', 'detalle' => 'COBRO EXCESIVO', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 48, 'respuestas_codigo_respuesta' => 'B048', 'literal' => 'J', 'detalle' => 'ENTREGA ERRONEA DE INFORMACIÓN A DEUDOR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 49, 'respuestas_codigo_respuesta' => 'B049', 'literal' => 'A', 'detalle' => 'REUSADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 50, 'respuestas_codigo_respuesta' => 'B050', 'literal' => 'A', 'detalle' => 'SUSPENDIDO POR CLIENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 50, 'respuestas_codigo_respuesta' => 'B050', 'literal' => 'B', 'detalle' => 'PASADO A COBRO JUDICIAL', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 50, 'respuestas_codigo_respuesta' => 'B050', 'literal' => 'C', 'detalle' => 'DEVUELTO POR TÉRMINO DE CICLO GESTIÓN', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 50, 'respuestas_codigo_respuesta' => 'B050', 'literal' => 'D', 'detalle' => 'PASADO A COBRO JUDICIAL HL', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 51, 'respuestas_codigo_respuesta' => 'B051', 'literal' => 'A', 'detalle' => 'CON EFECTIVO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 51, 'respuestas_codigo_respuesta' => 'B051', 'literal' => 'B', 'detalle' => 'CON CHEQUE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 52, 'respuestas_codigo_respuesta' => 'B052', 'literal' => 'A', 'detalle' => 'DIRECCION NO EXISTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 52, 'respuestas_codigo_respuesta' => 'B052', 'literal' => 'B', 'detalle' => 'NADIE EN DOMICILIO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 52, 'respuestas_codigo_respuesta' => 'B052', 'literal' => 'C', 'detalle' => 'NO DEJO PAGO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 52, 'respuestas_codigo_respuesta' => 'B052', 'literal' => 'D', 'detalle' => 'NO QUIZO PAGAR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 52, 'respuestas_codigo_respuesta' => 'B052', 'literal' => 'E', 'detalle' => 'DICE QUE PAGO ANTES', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 52, 'respuestas_codigo_respuesta' => 'B052', 'literal' => 'F', 'detalle' => 'NO VISITADO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 53, 'respuestas_codigo_respuesta' => 'B053', 'literal' => 'A', 'detalle' => 'POR ARCHIVO DE PAGOS', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 54, 'respuestas_codigo_respuesta' => 'B054', 'literal' => 'A', 'detalle' => 'DEUDOR INUBICABLE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 54, 'respuestas_codigo_respuesta' => 'B054', 'literal' => 'B', 'detalle' => 'DEUDOR NO QUIERE PAGAR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 54, 'respuestas_codigo_respuesta' => 'B054', 'literal' => 'C', 'detalle' => 'DEUDOR NO QUIERE DAR SOLUCION A SU DEUDA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 54, 'respuestas_codigo_respuesta' => 'B054', 'literal' => 'D', 'detalle' => 'SOLICITADO POR CLIENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 54, 'respuestas_codigo_respuesta' => 'B054', 'literal' => 'E', 'detalle' => 'EMPRESA EN QUIEBRA', 'tipos_gestion_idtipogestion' => 1, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 55, 'respuestas_codigo_respuesta' => 'B055', 'literal' => 'A', 'detalle' => 'SEGUIR GESTIONANDO CASO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 55, 'respuestas_codigo_respuesta' => 'B055', 'literal' => 'B', 'detalle' => 'CASO CON PROBLEMAS NO GESTIONAR', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 56, 'respuestas_codigo_respuesta' => 'B056', 'literal' => 'A', 'detalle' => 'EN ACSA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 57, 'respuestas_codigo_respuesta' => 'B057', 'literal' => 'A', 'detalle' => 'DESDE CLIENTE', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 57, 'respuestas_codigo_respuesta' => 'B057', 'literal' => 'B', 'detalle' => 'PAGO ACSA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 58, 'respuestas_codigo_respuesta' => 'B058', 'literal' => 'A', 'detalle' => 'DIRRECCION CORRECTA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 59, 'respuestas_codigo_respuesta' => 'B059', 'literal' => 'A', 'detalle' => 'NO SE REALIZA VISITA PROGRAMADA', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 59, 'respuestas_codigo_respuesta' => 'B059', 'literal' => 'B', 'detalle' => 'RECINTO CERRADO NO PERMITEN ACCESO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 59, 'respuestas_codigo_respuesta' => 'B059', 'literal' => 'C', 'detalle' => 'SECTOR PELIGROSO', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
			array('respuestas_idrespuesta' => 59, 'respuestas_codigo_respuesta' => 'B059', 'literal' => 'D', 'detalle' => 'SE NIEGAN A RECIBIR NOTIFICACION', 'tipos_gestion_idtipogestion' => 2, 'created_at' => date('Y-m-d')),
		);

		foreach (array_chunk($array_records, 1000) as $records) {
			\DB::table('respuestas_detalles')->insert($records);
        }
    }
}
