<?php

use Illuminate\Database\Seeder;

class RespuestasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        set_time_limit(0);

        $array_records = array (
			array('codigo' => 'B001', 'respuesta' => 'ABONANDO POR ARCHIVO DE POSTEO', 'detalle' => 'A', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B002', 'respuesta' => 'ABONANDO POR ARCHIVO DE POSTEO', 'detalle' => 'B', 'descripcion' => 'TERMINADO CON NUEVO DOCUMENTO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B003', 'respuesta' => 'ABONANDO POR CONVENIO', 'detalle' => 'A', 'descripcion' => 'EN CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B004', 'respuesta' => 'ABONO NO REBAJADO', 'detalle' => 'A', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B005', 'respuesta' => 'ABONO NO REBAJADO', 'detalle' => 'B', 'descripcion' => 'EN CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B006', 'respuesta' => 'ABONO NO REBAJADO', 'detalle' => 'D', 'descripcion' => 'DEPOSITO EN CTA.CTE.', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B007', 'respuesta' => 'ABONO O PAGO PARCIAL', 'detalle' => 'A', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B008', 'respuesta' => 'ASIGNACION A COBRADOR', 'detalle' => 'A', 'descripcion' => 'CLIENTE NUEVO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B009', 'respuesta' => 'ASIGNACION A COBRADOR', 'detalle' => 'B', 'descripcion' => 'REASIGNACIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B010', 'respuesta' => 'BUSQUEDA DE ANTECEDENTES', 'detalle' => 'K', 'descripcion' => 'CONTINUAR BUSQUEDA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B011', 'respuesta' => 'CASO REASIGNADO', 'detalle' => 'A', 'descripcion' => 'DEUDOR  REASIGNADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B012', 'respuesta' => 'CASO SIN FONO', 'detalle' => 'A', 'descripcion' => 'DEUDOR SIN  FONO  CONTACTO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B013', 'respuesta' => 'DEUDOR CORTA LLAMADO', 'detalle' => 'A', 'descripcion' => 'CLIENTE ESCUCHA Y CORTA LLAMADO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B014', 'respuesta' => 'DEUDOR DICE QUE IRÁ A CLIENTE', 'detalle' => 'A', 'descripcion' => 'A REGULARIZAR DEUDA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B015', 'respuesta' => 'DEUDOR DICE QUE IRÁ A CLIENTE', 'detalle' => 'B', 'descripcion' => 'PARA HACER RECLAMO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B016', 'respuesta' => 'DEUDOR NO PUEDE PAGAR', 'detalle' => 'A', 'descripcion' => 'PROBLEMAS ECONOMICOS', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B017', 'respuesta' => 'DEUDOR NO PUEDE PAGAR', 'detalle' => 'B', 'descripcion' => 'ESTA CESANTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B018', 'respuesta' => 'DEUDOR NO PUEDE PAGAR', 'detalle' => 'C', 'descripcion' => 'DEUDOR FALLECIO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B019', 'respuesta' => 'DEUDOR SOLICITA COPIA BOLETA O EST.CUENTA', 'detalle' => 'B', 'descripcion' => 'DEUDOR SOLICITA COPIA BOLETA O EST.CUENT', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B020', 'respuesta' => 'DEUDOR SOLICITA COPIA BOLETA O EST.CUENTA', 'detalle' => 'C', 'descripcion' => 'BOLETA ENVIADA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B021', 'respuesta' => 'DEUDOR SOLICITA QUE LO LLAMEN', 'detalle' => 'F', 'descripcion' => 'CLIENTE SOLICITA VOLVER A LLAMAR', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B022', 'respuesta' => 'DICE QUE COBRO NO CORRESPONDE', 'detalle' => 'A', 'descripcion' => 'DESCONOCE SERVICIO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B023', 'respuesta' => 'DICE QUE COBRO NO CORRESPONDE', 'detalle' => 'B', 'descripcion' => 'RENUNCIO A SERVICIO O CONTRATO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B024', 'respuesta' => 'DICE QUE COBRO NO CORRESPONDE', 'detalle' => 'C', 'descripcion' => 'TIENE RECLAMO SIN RESPONDER', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B025', 'respuesta' => 'DICE QUE COBRO NO CORRESPONDE', 'detalle' => 'D', 'descripcion' => 'DIFERENCIA EN DEUDA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B026', 'respuesta' => 'DICE QUE NO PAGARÁ', 'detalle' => 'A', 'descripcion' => 'TIENE RECLAMO AL CLIENTE SIN RESPONDER', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B027', 'respuesta' => 'DICE QUE NO PAGARÁ', 'detalle' => 'B', 'descripcion' => 'NIEGA PRODUCTO O SERVICIO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B028', 'respuesta' => 'DICE QUE NO PAGARÁ', 'detalle' => 'C', 'descripcion' => 'NO HA RECIBIDO FACTURA O BOLETA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B029', 'respuesta' => 'DICE QUE NO PAGARÁ', 'detalle' => 'D', 'descripcion' => 'ANULO CONTRATO, CUENTA O COMPRA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B030', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'A', 'descripcion' => 'OFICINA CLIENTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B031', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'B', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B032', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'C', 'descripcion' => 'SERVIAPAG / SENCILLITO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B033', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'D', 'descripcion' => 'OTRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B034', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'A', 'descripcion' => 'PIDE RETIRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B035', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'B', 'descripcion' => 'OFICINA CLIENTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B036', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'C', 'descripcion' => 'VENDRA A OFICINA ', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B037', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'D', 'descripcion' => 'ENVIARA DOCUMENTO (CHEQUE)', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B038', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'E', 'descripcion' => 'DEPOSITARA EN CTA. CTE.  OFICINA DE COBRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B039', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'F', 'descripcion' => 'ENVIARA GIRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B040', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'G', 'descripcion' => 'EN BANCO O PAC', 'descripcion' 'gestion' => 'Gestion valida'),
			array('codigo' => 'B041', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'H', 'descripcion' => 'EN SERVIPAG - SENCILLITO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B042', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'I', 'descripcion' => 'CUPON DE PAGO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B043', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'J', 'descripcion' => 'LLAMAR POR FECHA DE PAGO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B044', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'K', 'descripcion' => 'SOLICITA DETALLE DE DEUDA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B045', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'L', 'descripcion' => 'HARA CONVENIO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B046', 'respuesta' => 'DICE QUE PAGARÁ', 'detalle' => 'M', 'descripcion' => 'TRANSFERENCIA  OFICINA DE COBRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B047', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'A', 'descripcion' => 'OFICINA CLIENTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B048', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'B', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B049', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'C', 'descripcion' => 'OTRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B050', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'A', 'descripcion' => 'EN CLIENTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B051', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'B', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B052', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'C', 'descripcion' => 'EN SERVIPAG - SENCILLITO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B053', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'D', 'descripcion' => 'EN BANCO O TIENE PAC', 'descripcion' 'gestion' => 'Gestion valida'),
			array('codigo' => 'B054', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'E', 'descripcion' => 'A COBRADOR', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B055', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'F', 'descripcion' => 'CUPON DE PAGO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B056', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'G', 'descripcion' => 'ANULO EN CLIENTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B057', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'H', 'descripcion' => 'HIZO CONVENIO EN CLIENTE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B058', 'respuesta' => 'DICE QUE PAGÓ', 'detalle' => 'I', 'descripcion' => 'TIENE PAM FALABELLA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B059', 'respuesta' => 'DIRECCIÓN INCOMPLETA', 'detalle' => 'A', 'descripcion' => 'NO EXISTE NÚMERO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B060', 'respuesta' => 'DIRECCIÓN INCOMPLETA', 'detalle' => 'B', 'descripcion' => 'FALTA INFORMACIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B061', 'respuesta' => 'DIRECCIÓN INCOMPLETA', 'detalle' => 'C', 'descripcion' => 'DIRECCIÓN INCONSISTENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B062', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'A', 'descripcion' => 'SE CAMBIÓ', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B063', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'B', 'descripcion' => 'DESCONOCIDO EN DIRECCIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B064', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'A', 'descripcion' => 'NUEVOS ARRENDATARIOS', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B065', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'B', 'descripcion' => 'SE CAMBIO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B066', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'C', 'descripcion' => 'NO CONOCE A DEUDOR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B067', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'D', 'descripcion' => 'NO EXISTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B068', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'E', 'descripcion' => 'ES INUBICABLE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B069', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'F', 'descripcion' => 'Nº NO SE ENCONTRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B070', 'respuesta' => 'DIRECCIÓN NO CORRESPONDE', 'detalle' => 'G', 'descripcion' => 'DIRECCION INCOMPLETA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B071', 'respuesta' => 'EN GESTION', 'detalle' => 'A', 'descripcion' => 'DEUDOR EN GESTION', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B072', 'respuesta' => 'EN GESTION', 'detalle' => 'B', 'descripcion' => 'INTENTO LLAMADO NO LOGRADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B073', 'respuesta' => 'ENVIO DE CARTA  OFICINA DE COBRO', 'detalle' => 'D', 'descripcion' => 'INHABILITACION DE TAG', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B074', 'respuesta' => 'ENVIO DE INFROMACION A DEUDOR', 'detalle' => 'A', 'descripcion' => 'SOLICITA COPIA BOLETAS', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B075', 'respuesta' => 'ENVIO DE INFROMACION A DEUDOR', 'detalle' => 'B', 'descripcion' => 'SOLICITA DETALLE DEUDA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B076', 'respuesta' => 'ENVIO DE INFROMACION A DEUDOR', 'detalle' => 'C', 'descripcion' => 'SOLICITA FORMAS Y LUGARES DE PAGO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B077', 'respuesta' => 'ENVIO DE MAIL', 'detalle' => 'D', 'descripcion' => 'DESDE  OFICINA DE COBRO A DEUDOR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B078', 'respuesta' => 'ENVIO DE MAIL', 'detalle' => 'A', 'descripcion' => 'ENVIO MASIVO CON EXITO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B079', 'respuesta' => 'ENVIO DE MAIL', 'detalle' => 'B', 'descripcion' => 'ENVIO MASIVO SIN EXITO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B080', 'respuesta' => 'ENVIO DE MAIL', 'detalle' => 'C', 'descripcion' => 'RECEPCIÓN DE MAIL', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B081', 'respuesta' => 'ENVIO DE MENSAJE TEXTO', 'detalle' => 'A', 'descripcion' => 'ENVIADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B082', 'respuesta' => 'ENVIO DE MENSAJE TEXTO', 'detalle' => 'B', 'descripcion' => 'ENVÍO FALLIDO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B083', 'respuesta' => 'FALLECIDO', 'detalle' => 'A', 'descripcion' => 'FALLECIDO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B084', 'respuesta' => 'FONO FUERA DE SERVICIO', 'detalle' => 'A', 'descripcion' => 'F/SERVICIO, REPARACION, VACANTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B085', 'respuesta' => 'FONO NO CORRESPONDE A DEUDOR', 'detalle' => 'A', 'descripcion' => 'NUEVOS ARRENDATARIOS', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B086', 'respuesta' => 'FONO NO CORRESPONDE A DEUDOR', 'detalle' => 'B', 'descripcion' => 'SE CAMBIO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B087', 'respuesta' => 'FONO NO CORRESPONDE A DEUDOR', 'detalle' => 'C', 'descripcion' => 'NO CONOCE A DEUDOR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B088', 'respuesta' => 'FUERA DE AREA', 'detalle' => 'A', 'descripcion' => 'FUERA DE AREA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B089', 'respuesta' => 'GESTIÓN IVR, EXITOSA', 'detalle' => 'A', 'descripcion' => 'GRABACIÓN COMPLETA ENTREGADA A PERSONA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B090', 'respuesta' => 'GESTIÓN IVR, EXITOSA', 'detalle' => 'B', 'descripcion' => 'GRABACIÓN COMPLETA, CONTESTA GRABADORA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B091', 'respuesta' => 'GESTIÓN IVR, SIN CONTACTO', 'detalle' => 'A', 'descripcion' => 'FONO OCUPADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B092', 'respuesta' => 'GESTIÓN IVR, SIN CONTACTO', 'detalle' => 'B', 'descripcion' => 'FONO NO CONTESTA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B093', 'respuesta' => 'GESTIÓN IVR, SIN CONTACTO', 'detalle' => 'C', 'descripcion' => 'FONO FAX', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B094', 'respuesta' => 'GESTIÓN IVR, SIN CONTACTO', 'detalle' => 'D', 'descripcion' => 'FONO NO CONTACTADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B095', 'respuesta' => 'Hostigamiento', 'detalle' => 'A', 'descripcion' => 'ABIERTO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B096', 'respuesta' => 'Hostigamiento', 'detalle' => 'B', 'descripcion' => 'CERRADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B097', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'A', 'descripcion' => 'CARTA ENTREGADA DIRECCION CORRECTA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B098', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'B', 'descripcion' => 'DEUDOR CAMBIO DOMICILIO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B099', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'C', 'descripcion' => 'DEVUELTA, REENVIO POR CORREOS DE CHILE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B100', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'E', 'descripcion' => 'DEVUELTA POR FALTA DE DATOS', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B101', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'F', 'descripcion' => 'LUGAR SIN MORADORES', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B102', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'G', 'descripcion' => 'DIRECCION INSUFICIENTE O ERRONEA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B103', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'H', 'descripcion' => 'SE NIEGAN A RECIBIR CARTA, CARTA RECHAZA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B104', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'I', 'descripcion' => 'NO HAY QUIEN RECIBA CARTA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B105', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'D', 'descripcion' => 'LUGAR INACCESIBLE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B106', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'J', 'descripcion' => 'INFORMAN QUE DEUDOR NO VIVE EN DIRECCION', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B107', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'K', 'descripcion' => 'DICEN NO CONOCER A DEUDOR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B108', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'L', 'descripcion' => 'NUMERO NO UBICADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B109', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'M', 'descripcion' => 'DEUDOR NO EXISTE EN DIRECCION', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B110', 'respuesta' => 'INFORME DE CARTAS', 'detalle' => 'N', 'descripcion' => 'SIN GESTION', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B111', 'respuesta' => 'INGRESA RECLAMO POR WEB', 'detalle' => 'A', 'descripcion' => 'DESDE WEB  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B112', 'respuesta' => 'INGRESO CLIENTE POR ARCHIVO', 'detalle' => 'B', 'descripcion' => 'DESDE CLIENTES', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B113', 'respuesta' => 'INGRESO CLIENTE POR ARCHIVO', 'detalle' => 'C', 'descripcion' => 'DESDE  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B114', 'respuesta' => 'INUBICABLE', 'detalle' => 'A', 'descripcion' => 'TELEFONICAMENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B115', 'respuesta' => 'INUBICABLE', 'detalle' => 'B', 'descripcion' => 'POR DIRECCION Y TELEFONO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B116', 'respuesta' => 'INUBICABLE', 'detalle' => 'C', 'descripcion' => 'INUBICABLE ABSOLUTO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B117', 'respuesta' => 'LUGAR INACCESIBLE', 'detalle' => 'A', 'descripcion' => 'SECTOR PELIGROSO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B118', 'respuesta' => 'LUGAR INACCESIBLE', 'detalle' => 'B', 'descripcion' => 'RECINTO CERRADO, NO PERMITEN ACCESO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B119', 'respuesta' => 'MENSAJE', 'detalle' => 'A', 'descripcion' => 'CON TERCERO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B120', 'respuesta' => 'MENSAJE', 'detalle' => 'D', 'descripcion' => 'CONTESTA MENOR DE EDAD', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B121', 'respuesta' => 'NADIE EN DOMICILIO', 'detalle' => 'A', 'descripcion' => 'SE CONFIRMA DIRECCIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B122', 'respuesta' => 'NADIE EN DOMICILIO', 'detalle' => 'B', 'descripcion' => 'SE DEJA NOTIFICACIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B123', 'respuesta' => 'NADIE EN DOMICILIO', 'detalle' => 'C', 'descripcion' => 'NO SE CONFIRMA DIRECCIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B124', 'respuesta' => 'NO CONTESTA', 'detalle' => 'A', 'descripcion' => 'NO CONTESTA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B125', 'respuesta' => 'NO CONTESTA', 'detalle' => 'B', 'descripcion' => 'FONO OCUPADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B126', 'respuesta' => 'NO CONTESTA', 'detalle' => 'C', 'descripcion' => 'CONTESTA FAX', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B127', 'respuesta' => 'NO CONTESTA', 'detalle' => 'D', 'descripcion' => 'MENSAJE  EN GRABADORA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B128', 'respuesta' => 'NO CUMPLE ABONO', 'detalle' => 'A', 'descripcion' => 'TUVO PROBLEMAS ECONOMICOS', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B129', 'respuesta' => 'NO CUMPLE ABONO', 'detalle' => 'B', 'descripcion' => 'SOLICITA OTRA FECHA DE PAGO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B130', 'respuesta' => 'NOTIFICACIÓN BAJO PUERTA', 'detalle' => 'A', 'descripcion' => 'SE DEJA NOTIFICACIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B131', 'respuesta' => 'NOTIFICACIÓN CON DEUDOR OTERCERO', 'detalle' => 'A', 'descripcion' => 'CON TERCERO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B132', 'respuesta' => 'NOTIFICACIÓN CON DEUDOR OTERCERO', 'detalle' => 'B', 'descripcion' => 'CON DEUDOR SIN ACUERDO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B133', 'respuesta' => 'NOTIFICACIÓN CON DEUDOR OTERCERO', 'detalle' => 'C', 'descripcion' => 'DEUDOR IRA  A CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B134', 'respuesta' => 'NOTIFICACIÓN CON DEUDOR OTERCERO', 'detalle' => 'D', 'descripcion' => 'DEUDOR IRA A  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B135', 'respuesta' => 'NOTIFICACIÓN CON DEUDOR OTERCERO', 'detalle' => 'E', 'descripcion' => 'CON DEUDOR CON ACUERDO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B136', 'respuesta' => 'NOTIFICACIÓN CON TERCERO', 'detalle' => 'A', 'descripcion' => 'SE DEJA NOTIFICACIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B137', 'respuesta' => 'NOTIFICACIÓN CON TITULAR SIN ACUERDO', 'detalle' => 'A', 'descripcion' => 'SIN ACUERDO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B138', 'respuesta' => 'PAGO NO INGRESADO', 'detalle' => 'A', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B139', 'respuesta' => 'PAGO NO INGRESADO', 'detalle' => 'B', 'descripcion' => 'A COBRADOR  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B140', 'respuesta' => 'PAGO TOTAL', 'detalle' => 'A', 'descripcion' => 'EN  OFICINA DE COBRO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B141', 'respuesta' => 'PAGO TOTAL', 'detalle' => 'B', 'descripcion' => 'EN ATENCIÓN CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B142', 'respuesta' => 'PROBLEMA SIN SOLUCION DERIVADO A CLIENTE', 'detalle' => 'A', 'descripcion' => 'DEUDOR INDICA TENER PAC/PAT', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B143', 'respuesta' => 'PROBLEMA SIN SOLUCION DERIVADO A CLIENTE', 'detalle' => 'G', 'descripcion' => 'EMPRESA EN QUIEBRA', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B144', 'respuesta' => 'PROBLEMA SIN SOLUCION DERIVADO A CLIENTE', 'detalle' => 'H', 'descripcion' => 'DEUDOR FALLECIO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B145', 'respuesta' => 'PROBLEMA SIN SOLUCION DERIVADO A CLIENTE', 'detalle' => 'I', 'descripcion' => 'TIENE RECLAMO SIN RESPONDER', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B146', 'respuesta' => 'PROBLEMA SIN SOLUCION DERIVADO A CLIENTE', 'detalle' => 'J', 'descripcion' => 'TIENE NOTA DE CREDITO PENDIENE', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B147', 'respuesta' => 'PROBLEMA SIN SOLUCION DERIVADO A CLIENTE', 'detalle' => 'K', 'descripcion' => 'OTRO', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B148', 'respuesta' => 'RECLAMO', 'detalle' => 'A', 'descripcion' => 'Problemas de atención Ejecutivo', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B149', 'respuesta' => 'RECLAMO', 'detalle' => 'B', 'descripcion' => 'Fono no corresponde', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B150', 'respuesta' => 'RECLAMO', 'detalle' => 'C', 'descripcion' => 'Mail no corresponde', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B151', 'respuesta' => 'RECLAMO', 'detalle' => 'D', 'descripcion' => 'Dirección no corresponde', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B152', 'respuesta' => 'RECLAMO', 'detalle' => 'E', 'descripcion' => 'Cuenta ya regularizada', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B153', 'respuesta' => 'RECLAMO', 'detalle' => 'F', 'descripcion' => 'Desconoce deuda', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B154', 'respuesta' => 'RECLAMO', 'detalle' => 'G', 'descripcion' => 'Hostigamiento', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B155', 'respuesta' => 'RECLAMO', 'detalle' => 'H', 'descripcion' => 'Se entrega información de deuda a tercer', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B156', 'respuesta' => 'RECLAMO', 'detalle' => 'I', 'descripcion' => 'Cobro excesivo', 'gestion' => 'Gestion valida'),
			array('codigo' => 'B157', 'respuesta' => 'RECLAMO', 'detalle' => 'J', 'descripcion' => 'Entrega erronea de información a deudor', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B158', 'respuesta' => 'REHUSADO', 'detalle' => 'A', 'descripcion' => 'REUSADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B159', 'respuesta' => 'RETIRADO DE COBRANZA', 'detalle' => 'A', 'descripcion' => 'SUSPENDIDO POR CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B160', 'respuesta' => 'RETIRADO DE COBRANZA', 'detalle' => 'B', 'descripcion' => 'PASADO A  COBRO JUDICIAL', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B161', 'respuesta' => 'RETIRADO DE COBRANZA', 'detalle' => 'C', 'descripcion' => 'DEVUELTO POR TÉRMINO DE CICLO GESTIÓN', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B162', 'respuesta' => 'RETIRADO DE COBRANZA', 'detalle' => 'D', 'descripcion' => 'PASADO A COBRO JUDICIAL  HL', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B163', 'respuesta' => 'RETIRO CONCRETADO', 'detalle' => 'A', 'descripcion' => 'CON  EFECTIVO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B164', 'respuesta' => 'RETIRO CONCRETADO', 'detalle' => 'B', 'descripcion' => 'CON  CHEQUE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B165', 'respuesta' => 'RETIRO NO CONCRETADO', 'detalle' => 'A', 'descripcion' => 'DIRECCION NO EXISTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B166', 'respuesta' => 'RETIRO NO CONCRETADO', 'detalle' => 'B', 'descripcion' => 'NADIE EN DOMICILIO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B167', 'respuesta' => 'RETIRO NO CONCRETADO', 'detalle' => 'C', 'descripcion' => 'NO DEJO PAGO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B168', 'respuesta' => 'RETIRO NO CONCRETADO', 'detalle' => 'D', 'descripcion' => 'NO QUIZO PAGAR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B169', 'respuesta' => 'RETIRO NO CONCRETADO', 'detalle' => 'E', 'descripcion' => 'DICE QUE PAGO ANTES', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B170', 'respuesta' => 'RETIRO NO CONCRETADO', 'detalle' => 'F', 'descripcion' => 'NO VISITADO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B171', 'respuesta' => 'REVERSA DE PAGO CLIENTE', 'detalle' => 'A', 'descripcion' => 'POR  ARCHIVO  DE PAGOS', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B172', 'respuesta' => 'SE RECOMIENDA JUDICIAL', 'detalle' => 'A', 'descripcion' => 'DEUDOR INUBICABLE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B173', 'respuesta' => 'SE RECOMIENDA JUDICIAL', 'detalle' => 'B', 'descripcion' => 'DEUDOR NO QUIERE PAGAR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B174', 'respuesta' => 'SE RECOMIENDA JUDICIAL', 'detalle' => 'C', 'descripcion' => 'DEUDOR NO QUIERE DAR SOLUCION A SU DEUDA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B175', 'respuesta' => 'SE RECOMIENDA JUDICIAL', 'detalle' => 'D', 'descripcion' => 'SOLICITADO POR CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B176', 'respuesta' => 'SE RECOMIENDA JUDICIAL', 'detalle' => 'E', 'descripcion' => 'EMPRESA  EN QUIEBRA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B177', 'respuesta' => 'SOLUCION CLIENTE', 'detalle' => 'A', 'descripcion' => 'SEGUIR GESTIONANDO CASO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B178', 'respuesta' => 'SOLUCION CLIENTE', 'detalle' => 'B', 'descripcion' => 'CASO CON PROBLEMAS NO GESTIONAR', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B179', 'respuesta' => 'TERMINADO CON CONVENIO', 'detalle' => 'A', 'descripcion' => 'EN  ACSA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B180', 'respuesta' => 'TERMINADO POR ARCHIVO DE POSTEO', 'detalle' => 'A', 'descripcion' => 'DESDE CLIENTE', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B181', 'respuesta' => 'TERMINADO POR ARCHIVO DE POSTEO', 'detalle' => 'B', 'descripcion' => 'PAGO ACSA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B184', 'respuesta' => 'VERIFICACION DE DIRECCION', 'detalle' => 'A', 'descripcion' => 'DIRRECCION  CORRECTA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B185', 'respuesta' => 'VISITA NO CONCRETADA', 'detalle' => 'A', 'descripcion' => 'NO SE REALIZA VISITA  PROGRAMADA', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B186', 'respuesta' => 'VISITA NO CONCRETADA', 'detalle' => 'B', 'descripcion' => 'RECINTO CERRADO NO PERMITEN ACCESO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B187', 'respuesta' => 'VISITA NO CONCRETADA', 'detalle' => 'C', 'descripcion' => 'SECTOR PELIGROSO', 'gestion' => 'Gestion no valida'),
			array('codigo' => 'B188', 'respuesta' => 'VISITA NO CONCRETADA', 'detalle' => 'D', 'descripcion' => 'SE NIEGAN A RECIBIR NOTIFICACION', 'gestion' => 'Gestion no valida'),

        );

        foreach (array_chunk($array_records, 1000) as $records) {
              \DB::table('respuestas')->insert($records);
        }
    }
}
